#  -*- mode: org; coding: utf-8; -*-
#+TITLE: Worg 的简体中文翻译

[[http://orgmode.org/][Org-mode]] 是一个用纯文本来管理复杂生活的强大系统。它可以将你所有的笔记、脑图、待
办事项列表、日历、每天计划及项目日程无缝地嵌入到一个系统中，方便你搜索、加密、备
份、同步 (比如 Dropbox)、导入／导出，包括在移动设备上访问。它还可用于创作网页和
文档。目前, Org-mode 已经成为 Emacs 默认发行套件的一部分。

[[http://orgmode.org/worg/][Worg]] 是由 Org-mode 的粉丝们志愿建立的社区，收集了一些教程、好主意、代码片断等。

[[https://github.com/smth-emacs/worg-zh][Worg-zh]] 是由水木社区的 Emacs 爱好者们自发组织的一个翻译项目，试图将大家参考比较
多的一些 Org-mode 文档翻译成中文，方便更多的初学者（也包括有经验的用户）。另外，
此项目将会添加一些中文处理所特有的内容。期望此项目能够以英文的 Worg 为起点，形成
一个以中文为母语的 Org-mode 粉丝们所乐见的参考文档集合。

* 原始文档

英文的原始文档参见：
  - 网页 -- http://orgmode.org/worg/
  - git  -- http://orgmode.org/cgit.cgi/worg.git/

* 项目约定
** 软件约定

参与本项目的翻译，你至少应该备有如下软件：
- Emacs, 如无特别说明，以 Emacs 24 为起点。
- Org-mode, 如无特别说明，以 8.0 版本为起点。
- Git, 以 1.7 版本为起点。

** Git 分支约定

仓库 *smth-emacs/worg-zh* 有三个分支：
- *master* -- 用于保存翻译并核对好的内容，由管理员管理。
- *devel* -- 进展中的分支，由于保存部分翻译，或者新添加待审核的内容。
- *gh-pages* -- 由 master 分支生成的 HTML 页面。

志愿者提交的 =pull request= 内容应首先 merge 到 =devel= 分支，等管理员审核后再合
并到 =master= 分支中去。为保持 =master= 与 =devel= 的分支历史记录的清晰，管理员
在执行 =git merge= 操作时应该用参数 =--no-ff=, 即避免 =fast-forward= 合并。

志愿者在翻译时，可按如下流程执行：
1. 在 GitHub 上 =fork= 本仓库到自己的账号下，比如 *exaos/worg-zh*
2. 克隆自己仓库 worg-zh 到本地。
   #+BEGIN_EXAMPLE
   git clone git@github.com:exaos/worg-zh.git
   #+END_EXAMPLE
3. 添加一个英文的远程仓库，并提取其仓库内容。
   #+BEGIN_EXAMPLE
   git remote add cgit-worg git://orgmode.org/worg.git
   git fetch --all
   #+END_EXAMPLE
4. 把英文版本的内容创建一个本地分支，比如 =worg=:
   #+BEGIN_EXAMPLE
   git branch -b worg cgit-worg/master
   #+END_EXAMPLE
5. 从英文仓库中提取新版本的页面开始翻译。比如英文版本的 =worg-setup.org= 文件比
   本地新，则可以这样提出文件：
   #+BEGIN_EXAMPLE
   git co worg -- worg-setup.org
   #+END_EXAMPLE
6. 添加 =smth-emacs/worg-zh= 为远程仓库，并为 =pull request= 创建新的分支。
   #+BEGIN_EXAMPLE
   git remote add gh-smth git://github.com/smth-emacs/worg-zh.git
   git fetch --all
   git branch -b for-smth gh-smth/devel
   #+END_EXAMPLE
7. 在你自己的 =master= 分支下可以任意修改并 =commit=, 感觉完善并可以提交给
   =smth-emacs/worg-zh= 了，先切换到 =for-smth= 分支，使用 =--no-ff= 选项进行
   =merge= 操作:
   #+BEGIN_EXAMPLE
   git checkout for-smth
   git merge --no-ff master
   git push origin for-smth:for-smth
   #+END_EXAMPLE
8. 然后在 github 上用你的 =for-smth= 分支向 =smth-emacs/worg-zh= 发起 =pull
   request=. 管理员收到请求时，会首先合并到 =devel= 分支下，检查无误后，再进一步
   合并到 =master= 分支中。

对于 =smth-emacs/worg-zh= 已经包含有的文件：
- 如果已经有中文翻译，但未完成的，建议继续完成。
- 如果还没有中文翻译，并且有新的英文版本的，按上述步骤 5) 中添加新文件，但应该把
  英文版本的 commit 号包含在提交历史中。比如：
  #+BEGIN_EXAMPLE
  git commit -m "Fetch new version worg-setup.org: worg.git-ref:9531016"
  #+END_EXAMPLE
- 如果中文翻译已经完成，并且有新的英文版本的，应将英文版本检出其它文件名，根据它
  直接更新已经翻译的文件。

** 译文及名词

为符合 GNU 一贯的风格，在译文中 Org mode 可称为 Org, Org-mode 或 Orgmode, 尽量不
要用 org-mode.

* 参加须知

请在水木社区的 [[http://www.newsmth.net/nForum/#!board/Emacs][Emacs 版]] 留言。
- http://www.newsmth.net/nForum/#!board/Emacs

* 更新记录
- <2013-05-10 20:45> 初始化 worg-zh 项目，合并 worg.git
  - worg.git -- [[http://orgmode.org/cgit.cgi/worg.git/commit/?id=953101622916024cf09e48da287da8605e1a58ad][ref:953101622916024cf09e48da287da8605e1a58ad]]
